# Generated by Django 3.2.7 on 2021-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
